
function Y = makeSphericalBasis(Nx, Ny, Nz)
    alpha = double(acos(Nz));
    beta = double(atan2(Ny, Nx + eps));
    cos_a = double(cos(alpha));
    sin_a = double(sin(alpha));
    sin_n_b = double(sin(-beta));
    sin_n_2b = double(sin(-2 * beta));
    sin_n_3b = double(sin(-3 * beta));
    sin_n_4b = double(sin(-4 * beta));
    sin2_a = double(sin_a.^2);
    cos2_a = double(cos_a.^2);
    sin3_a = double(sin2_a .* sin_a);
    cos3_a = double(cos2_a .* cos_a);
    sin4_a = double(sin2_a.^2);
    cos4_a = double(cos2_a.^2);
    cos_b = double(cos(beta));
    cos_2b = double(cos(2 * beta));
    cos_3b = double(cos(3 * beta));
    cos_4b = double(cos(3 * beta));

    y11 = 0.5 * sqrt(3 / (2 * pi)) * sin_a;
    y22 = 0.25 * sqrt(15 / (2 * pi)) * sin2_a;
    y21 = 0.5 * sqrt(15 / (2 * pi)) * sin_a .* cos_a;
    y44 = 0.1875 * sqrt(35 / (2 * pi)) * sin4_a;
    y43 = 0.375 * sqrt(35 / pi) * sin3_a .* cos_a;
    y42 = 0.375 * sqrt(5 / (2 * pi)) * sin2_a .* (7 * cos2_a - 1);
    y41 = 0.375 * sqrt(5 / pi) * sin_a .* (7 * cos3_a - 3 * cos_a);
    Y = {   sqrt(1 / pi) * ones(size(alpha)),...
            y11 .* sin_n_b,...
            0.5 .* sqrt(3 / pi) * cos_a,...
            -y11 .* cos_b,...
            y22 .* sin_n_2b,...
            y21 .* sin_n_b,...
            0.25 * sqrt(5 / pi) * (3 * cos2_a - 1),...
            -y21 .* cos_b,...
            y22 .* cos_2b,...
            y44 .* sin_n_4b,...
            y43 .* sin_n_3b,...
            y42 .* sin_n_2b,...
            y41 .* sin_n_b,...
            0.1875 * sqrt(1 / pi) * (35 * cos4_a - 30 * cos2_a + 3),...
            -y41 .* cos_b,...
            y42 .* cos_2b,...
            -y43 .* cos_3b,...
            y44 .* cos_4b
        };

    Y = cell2mat(Y);
end